### PR TITLE
Added reloading of company table after company removal.

### PR DESCRIPTION
**Pull request by apollo13**
I couldn't get it to run locally (I tried in a docker container, but there was no postgres in there ;)), but this should fix the issue mentioned in https://github.com/unpoly/unpoly/discussions/265 (company list does not reload after company deletion)

### CODE REVIEW

**Comment by adam12** [comment]
> but there was no postgres in there

I modified my copy locally to use sqlite because I ran into a similar issue. This might be worth bubbling up as a separate contribution, if @triskweline is accepting.

**Comment by apollo13** [comment]
>  I modified my copy locally to use sqlite because I ran into a similar issue. 

That would help a lot -- it is the first time I ever touched ruby/rails and as such I was happy that I could start the server at all :)

**Comment by apollo13** [comment]
> Is it hard to write a Docker container that provides Ruby and Postgres? I'm doing all my development locally, so I don't know.

Inside one container? Yes kinda hard. I would have used an extra docker container via docker-compose but the app tried to use a local socket and I didn't bother figuring out how to change that (please note I never wrote a line of ruby).

That said, developing locally probably works just fine. I just opted for the docker container because it complained that the ruby shipped with fedora is to new.

**Comment by adam12** [comment]
Thanks for the PR :+1:

**Pull request merged**
